In [25]:
import numpy as np
import torch

In [58]:
ints = torch.tensor([0, 1, 1, 0]).unsqueeze(1)
predicts = torch.rand(4,2)

print(ints)
print(predicts)

torch.gather(predicts, 1, ints)

tensor([[0],
        [1],
        [1],
        [0]])
tensor([[0.1387, 0.1886],
        [0.0949, 0.9634],
        [0.4631, 0.9069],
        [0.6541, 0.6591]])


tensor([[0.1387],
        [0.9634],
        [0.9069],
        [0.6541]])

In [108]:
ints = torch.tensor([0, 1, 1, 3])
# print(ints.shape)



index_nrs = (ints == 1).nonzero().squeeze()
print(index_nrs)
# print(index_nrs.shape)


ints.scatter(0, index_nrs, 100)

tensor([1, 2])


tensor([  0, 100, 100,   3])